<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: Call to undefined function WPPFW\Plugin\plugin_dir_url() in /Users/giacomosardo/Local Sites/weglad/app/public/wp-content/plugins/wp-config-file-editor/vendor/xptrdev/WPPluginFramework/Include/Plugin/PluginBase.php on line <i>126</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: Call to undefined function WPPFW\Plugin\plugin_dir_url() in /Users/giacomosardo/Local Sites/weglad/app/public/wp-content/plugins/wp-config-file-editor/vendor/xptrdev/WPPluginFramework/Include/Plugin/PluginBase.php on line <i>126</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>406400</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Users/giacomosardo/Local Sites/weglad/app/public/wp-content/plugins/wp-config-file-editor/wp-config-file-editor.php' bgcolor='#eeeeec'>.../wp-config-file-editor.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>415968</td><td bgcolor='#eeeeec'>WCFE\Plugin::plug(  )</td><td title='/Users/giacomosardo/Local Sites/weglad/app/public/wp-content/plugins/wp-config-file-editor/wp-config-file-editor.php' bgcolor='#eeeeec'>.../wp-config-file-editor.php<b>:</b>268</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>416288</td><td bgcolor='#eeeeec'>WCFE\Plugin->__construct(  )</td><td title='/Users/giacomosardo/Local Sites/weglad/app/public/wp-content/plugins/wp-config-file-editor/wp-config-file-editor.php' bgcolor='#eeeeec'>.../wp-config-file-editor.php<b>:</b>254</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0053</td><td bgcolor='#eeeeec' align='right'>583152</td><td bgcolor='#eeeeec'>WCFE\Plugin->__construct(  )</td><td title='/Users/giacomosardo/Local Sites/weglad/app/public/wp-content/plugins/wp-config-file-editor/wp-config-file-editor.php' bgcolor='#eeeeec'>.../wp-config-file-editor.php<b>:</b>95</td></tr>
</table></font>
