<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: Call to undefined function get_option() in /Users/giacomosardo/Local Sites/weglad/app/public/wp-content/plugins/static-html-output-plugin/plugin/WP2Static/Options.php on line <i>2</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: Call to undefined function get_option() in /Users/giacomosardo/Local Sites/weglad/app/public/wp-content/plugins/static-html-output-plugin/plugin/WP2Static/Options.php on line <i>2</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>405088</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Users/giacomosardo/Local Sites/weglad/app/public/wp-content/plugins/static-html-output-plugin/wp2static.php' bgcolor='#eeeeec'>.../wp2static.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0005</td><td bgcolor='#eeeeec' align='right'>414304</td><td bgcolor='#eeeeec'>WP2Static_Controller::init(  )</td><td title='/Users/giacomosardo/Local Sites/weglad/app/public/wp-content/plugins/static-html-output-plugin/wp2static.php' bgcolor='#eeeeec'>.../wp2static.php<b>:</b>28</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0005</td><td bgcolor='#eeeeec' align='right'>414304</td><td bgcolor='#eeeeec'>WP2Static_Controller::getInstance(  )</td><td title='/Users/giacomosardo/Local Sites/weglad/app/public/wp-content/plugins/static-html-output-plugin/plugin/WP2Static.php' bgcolor='#eeeeec'>.../WP2Static.php<b>:</b>2</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0005</td><td bgcolor='#eeeeec' align='right'>414472</td><td bgcolor='#eeeeec'>WP2Static_Options->__construct(  )</td><td title='/Users/giacomosardo/Local Sites/weglad/app/public/wp-content/plugins/static-html-output-plugin/plugin/WP2Static.php' bgcolor='#eeeeec'>.../WP2Static.php<b>:</b>2</td></tr>
</table></font>
